//Burger reducer
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const INIT_INGREDIENTS_FAIL = "INIT_INGREDIENTS_FAIL";
export const SET_PRICE = "SET_PRICE";
//order reducer
export const START_LOAD_ORDERS = "START_LOAD_ORDERS";
export const SET_ORDERS = "SET_ORDERS";
export const INIT_ORDERS_FAIL = "INIT_ORDERS_FAIL";
